"""Documentation & Metadata Agent — LLM writes README + column descriptions."""
from __future__ import annotations

from .base import Agent, RunContext
from .. import llm


SYSTEM_PROMPT = """You are the Documentation & Metadata Agent.
Write a concise README.md for a newly onboarded enterprise data product.
Include: overview, ownership, SLA, downstream consumers, runbook, and any
governance notes (PII, masking, retention). Use markdown, no HTML.
Return the README as plain markdown, without any code fences around the whole doc."""


class DocsAgent(Agent):
    id = "docs"
    name = "Documentation & Lineage Agent"
    stage = "docs"

    async def run(self, ctx: RunContext) -> dict:
        self.started(ctx)
        req = ctx.request
        pii_summary = ctx.outputs.get("pii", {}).get("by_class", {})

        self.emit(ctx, "Requesting README from LLM…")
        prompt = (
            f"Source name: {req['source_name']}\n"
            f"Type: {req['source_type']}\n"
            f"Refresh: {req['refresh']}\n"
            f"Business owner: {req.get('business_owner','Dealer Sales COE')}\n"
            f"Steward: shanmugapriya.kandasamy@cognizant.com\n"
            f"Downstream consumers: Power BI 'Dealer Sales — Certified', reverse-ETL 'crm_scoring_v2'.\n"
            f"PII summary: {pii_summary}\n"
            "Keep the README ~40-60 lines."
        )
        readme = llm.complete(SYSTEM_PROMPT, prompt, temperature=0.3, max_tokens=1200)
        if not readme:
            readme = _fallback_readme(req)

        p1 = ctx.write_text(("docs", "README.md"), readme)
        self.artifact(ctx, "README.md", p1, preview=readme)

        # Static exposure + lineage summary
        exposure = _render_exposure_yml()
        p2 = ctx.write_text(("docs", "exposures.yml"), exposure)
        self.artifact(ctx, "exposures.yml", p2, preview=exposure)

        lineage = _render_lineage()
        p3 = ctx.write_json(("docs", "lineage.json"), lineage)
        self.artifact(ctx, "lineage.json", p3, preview="")

        ctx.outputs["docs"] = {"readme_bytes": len(readme), "lineage_nodes": len(lineage["nodes"])}
        self.done(ctx, "README, catalog entry, and lineage graph published")
        return ctx.outputs["docs"]


def _fallback_readme(req: dict) -> str:
    return f"""# {req['source_name']} — Andersen Data Platform

Auto-generated by the Cognizant Documentation & Metadata Agent.

## Overview
Ingests {req['source_name']} ({req['source_type']}) every {req['refresh']}.
Data lands in `DP_RAW.RAW_DEALER_SALES`, transformed by dbt to staging and
mart layers, and exposed to Power BI as a certified dataset.

## Ownership
- Business owner: **{req.get('business_owner','Dealer Sales COE')}**
- Technical owner: **Data Platform team**
- Steward: shanmugapriya.kandasamy@cognizant.com

## SLA
- Refresh: every {req['refresh']}
- Lag alert: > 15 minutes
- DQ blocker rules must be green for run publication

## Downstream consumers
- Power BI · *Dealer Sales — Certified*
- Reverse-ETL job `crm_scoring_v2` (Hightouch)

## Runbook
1. On freshness alert, inspect `DP_META.SOURCE_FRESHNESS`.
2. On DQ failure, review `DP_META.DQ_RESULTS`, filter `domain='dealer_sales'`.
3. Escalation: `#dealer-sales-oncall`, then dealer_sales_coe@andersen.
"""


def _render_exposure_yml() -> str:
    return """# dbt/models/dealer_sales/exposures.yml
version: 2
exposures:
  - name: powerbi_dealer_sales_certified
    label: "Dealer Sales — Certified"
    type: dashboard
    maturity: high
    url: https://app.powerbi.com/groups/...
    owner: {name: Dealer Sales COE, email: dealer_sales_coe@andersen}
    depends_on: [ref('dim_customer'), ref('dim_product'), ref('fct_order')]
"""


def _render_lineage() -> dict:
    return {
        "nodes": [
            {"id": "src",   "label": "DealerSalesCRM",  "type": "source"},
            {"id": "raw_c", "label": "RAW.CUSTOMER",   "type": "raw"},
            {"id": "raw_o", "label": "RAW.ORDER",      "type": "raw"},
            {"id": "raw_p", "label": "RAW.PRODUCT",    "type": "raw"},
            {"id": "stg_c", "label": "stg_customer",   "type": "staging"},
            {"id": "stg_o", "label": "stg_order",      "type": "staging"},
            {"id": "stg_p", "label": "stg_product",    "type": "staging"},
            {"id": "dim_c", "label": "dim_customer",   "type": "mart"},
            {"id": "dim_p", "label": "dim_product",    "type": "mart"},
            {"id": "fct_o", "label": "fct_order",      "type": "mart"},
            {"id": "pbi",   "label": "Power BI",       "type": "bi"},
        ],
        "edges": [
            ["src", "raw_c"], ["src", "raw_o"], ["src", "raw_p"],
            ["raw_c", "stg_c"], ["raw_o", "stg_o"], ["raw_p", "stg_p"],
            ["stg_c", "dim_c"], ["stg_p", "dim_p"], ["stg_o", "fct_o"],
            ["dim_c", "fct_o"], ["dim_p", "fct_o"],
            ["dim_c", "pbi"], ["dim_p", "pbi"], ["fct_o", "pbi"],
        ],
    }
